# Digital Ocean App Platform Configuration
# =========================================
# Deploy: doctl apps create --spec app.yaml
# Update: doctl apps update <app-id> --spec app.yaml

name: sip-dialer
region: nyc

# =============================================================================
# SERVICES
# =============================================================================
services:
  # ---------------------------------------------------------------------------
  # Frontend (React + Nginx)
  # ---------------------------------------------------------------------------
  - name: frontend
    github:
      repo: YOUR_GITHUB_USERNAME/sip-dialer
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    dockerfile_path: docker/frontend/Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME

  # ---------------------------------------------------------------------------
  # API Gateway (FastAPI)
  # ---------------------------------------------------------------------------
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/sip-dialer
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: docker/api-gateway/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    routes:
      - path: /api
        preserve_path_prefix: true
    health_check:
      http_path: /api/v1/health
      initial_delay_seconds: 15
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      # Database (injected from managed DB)
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      # Redis (injected from managed Redis)
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      # Security (set as secrets in DO console)
      - key: JWT_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET
      # S3/Spaces
      - key: S3_ENDPOINT
        scope: RUN_TIME
        value: ${spaces.ORIGIN_ENDPOINT}
      - key: S3_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_BUCKET
        scope: RUN_TIME
        value: sip-dialer-audio
      - key: S3_SECURE
        scope: RUN_TIME
        value: "true"
      # CORS
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: https://${APP_DOMAIN}
      # App
      - key: APP_ENV
        scope: RUN_TIME
        value: production
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO

  # ---------------------------------------------------------------------------
  # Celery Worker
  # ---------------------------------------------------------------------------
  - name: worker
    github:
      repo: YOUR_GITHUB_USERNAME/sip-dialer
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: docker/celery/Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    run_command: celery -A workers.celery_app worker --loglevel=info --concurrency=4
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: CELERY_BROKER_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: CELERY_RESULT_BACKEND
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: S3_ENDPOINT
        scope: RUN_TIME
        value: ${spaces.ORIGIN_ENDPOINT}
      - key: S3_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_BUCKET
        scope: RUN_TIME
        value: sip-dialer-audio
      - key: S3_SECURE
        scope: RUN_TIME
        value: "true"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO
      # SMTP (for email notifications)
      - key: SMTP_HOST
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_PORT
        scope: RUN_TIME
        value: "587"
      - key: SMTP_USERNAME
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_FROM_EMAIL
        scope: RUN_TIME
        value: noreply@yourdomain.com
      - key: SMTP_USE_TLS
        scope: RUN_TIME
        value: "true"
      - key: SMTP_ENABLED
        scope: RUN_TIME
        value: "true"

  # ---------------------------------------------------------------------------
  # Celery Beat (Scheduler)
  # ---------------------------------------------------------------------------
  - name: scheduler
    github:
      repo: YOUR_GITHUB_USERNAME/sip-dialer
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: docker/celery/Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    run_command: celery -A workers.celery_app beat --loglevel=info
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: CELERY_BROKER_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO

# =============================================================================
# DATABASES
# =============================================================================
databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb
    num_nodes: 1

# =============================================================================
# Note: Redis and Spaces must be created separately
# =============================================================================
#
# 1. Create Redis cluster:
#    doctl databases create sip-dialer-redis --engine redis --size db-s-1vcpu-1gb --region nyc1
#
# 2. Create Spaces bucket:
#    doctl spaces create sip-dialer-audio --region nyc3
#
# 3. After deployment, set secrets in DO Console:
#    - JWT_SECRET_KEY
#    - ENCRYPTION_KEY
#    - S3_ACCESS_KEY
#    - S3_SECRET_KEY
#    - SMTP_HOST, SMTP_USERNAME, SMTP_PASSWORD (if using email)
#
# 4. Update REDIS_URL in app settings with the Redis connection string
#
# =============================================================================
# DIALER ENGINE - NOT DEPLOYED ON APP PLATFORM
# =============================================================================
# The dialer engine requires:
# - UDP ports for SIP (5061) and RTP (10000-20000)
# - Access to UCM via VPN tunnel
# - Host networking mode
#
# Deploy separately on the VPN Gateway Droplet using docker-compose.dialer.yml
# =============================================================================
